
function getCurrentUser() {
    const stored = localStorage.getItem('wildlife_conservation_user');
    if (stored) {
        return JSON.parse(stored);
    }
    return null;
}

function logout() {
    localStorage.removeItem('wildlife_conservation_user');
    window.location.href = 'index.html';
}

function formatDate() {
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    return new Date().toLocaleDateString('en-US', options);
}

function updateDateTime() {
    const dateElement = document.getElementById('currentDate');
    if (dateElement) {
        dateElement.textContent = formatDate();
    }
}

function loadDashboardData() {
    const user = getCurrentUser();
    
    if (!user) {
        window.location.href = 'index.html';
        return;
    }
    
    document.getElementById('welcomeUserName').textContent = user.name;
    document.getElementById('sidebarUserName').textContent = user.name;
    document.getElementById('sidebarUserRole').textContent = user.role;
    
    const userAvatar = document.getElementById('userAvatar');
    if (user.role === 'Administrator') {
        userAvatar.innerHTML = '👑';
    } else if (user.role === 'Researcher') {
        userAvatar.innerHTML = '🔬';
    } else {
        userAvatar.innerHTML = '🛡️';
    }
    
    const animals = getAnimals();
    const sightings = getSightings();
    const locations = getLocations();
    
    document.getElementById('totalAnimals').textContent = animals.length;
    document.getElementById('totalSightings').textContent = sightings.length;
    document.getElementById('totalLocations').textContent = locations.length;
    document.getElementById('totalResearchers').textContent = Math.floor(Math.random() * 20) + 8;
    
    const recentSightings = [...sightings].reverse().slice(0, 5);
    const sightingsHtml = recentSightings.map(sighting => `
        <div class="timeline-item">
            <div class="timeline-icon">
                <i class="fas fa-camera"></i>
            </div>
            <div class="timeline-content">
                <div class="timeline-title">
                    <strong>${sighting.animal_name}</strong>
                    <span class="timeline-date">${sighting.date}</span>
                </div>
                <div class="timeline-location">
                    <i class="fas fa-location-dot"></i> ${sighting.location}
                </div>
                <div class="timeline-count">
                    <i class="fas fa-charging-station"></i> ${sighting.count} animals observed
                </div>
                <div class="timeline-observer">
                    <i class="fas fa-user-check"></i> ${sighting.observer}
                </div>
            </div>
        </div>
    `).join('');
    
    document.getElementById('recentSightingsList').innerHTML = sightingsHtml || '<div class="empty-state"><i class="fas fa-inbox"></i><p>No sightings recorded yet</p></div>';
    
    const sortedAnimals = [...animals].sort((a, b) => b.population - a.population).slice(0, 5);
    const speciesHtml = sortedAnimals.map((animal, index) => {
        const percentage = (animal.population / sortedAnimals[0].population) * 100;
        return `
            <div class="species-item">
                <div class="species-info">
                    <span class="species-rank">#${index + 1}</span>
                    <span class="species-name">${animal.name}</span>
                    <span class="species-population">${animal.population.toLocaleString()}</span>
                </div>
                <div class="species-bar">
                    <div class="species-bar-fill" style="width: ${percentage}%;"></div>
                </div>
            </div>
        `;
    }).join('');
    
    document.getElementById('speciesList').innerHTML = speciesHtml;
}

function generateReport() {
    const user = getCurrentUser();
    const animals = getAnimals();
    const sightings = getSightings();
    
    const reportContent = `
        WILDLIFE CONSERVATION REPORT
        Generated by: ${user.name} (${user.role})
        Date: ${formatDate()}
        ----------------------------------------
        
        SUMMARY STATISTICS:
        - Total Protected Species: ${animals.length}
        - Total Sightings Recorded: ${sightings.length}
        - Active Conservation Sites: ${getLocations().length}
        
        SPECIES BREAKDOWN:
        ${animals.map(a => `- ${a.name}: ${a.population.toLocaleString()} individuals (${a.conservation_status})`).join('\n')}
        
        RECENT ACTIVITY:
        ${sightings.slice(-3).map(s => `- ${s.animal_name} sighted at ${s.location} on ${s.date} (${s.count} animals)`).join('\n')}
        
        ----------------------------------------
        Wildlife Conservation Monitoring System
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wildlife_report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    alert('📄 Report generated and downloaded successfully!');
}

document.addEventListener('DOMContentLoaded', () => {
    updateDateTime();
    loadDashboardData();
    setInterval(updateDateTime, 60000);
});